name: Run Python Script

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install python-chess
          pip install stockfish
          pip install pyngrok
          sudo apt-get update
          sudo apt-get install -y stockfish

      - name: Run backend runner
        run: python backendrunner.py